steps:
# Update submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git submodule init
    git submodule update
# build hugo site
# See ./hugo-builder/README.md
# - name: 'gcr.io/$PROJECT_ID/hugo-builder' #prev command
- name: 'cibuilds/hugo:0.65.1'
  args:
    - 'HUGO_ENV=production hugo'
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA']
# cleanup existing containers
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '$_SSH_STRING'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - '$_ZONE'
  - '--'
  - 'docker container stop $$(docker container ls -aq) && docker container rm $$(docker container ls -aq)'
# redeploy with new container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '$_SSH_STRING'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - '$_ZONE'
  - '--'
  - 'docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v $_HOME/.caddy:/root/.caddy gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
images:
 - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'



