# In this directory, run the following command to build this builder.
# $ gcloud --project=devops-directive-project builds submit . --config=cloudbuild.yaml --substitutions COMMIT_SHA=manual

steps:
# get the submodules
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--recursive']
# build hugo site
# See ./hugo-builder/README.md
- name: 'gcr.io/$PROJECT_ID/hugo-builder'
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/devops-directive-caddy:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/devops-directive-caddy:$COMMIT_SHA']
# cleanup existing containers
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'palas@cos-f1-micro'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - 'us-central1-a'
  - '--'
  - 'docker container stop $$(docker container ls -aq) && docker container rm $$(docker container ls -aq)'
# redeploy with new container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'palas@cos-f1-micro'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - 'us-central1-a'
  - '--'
  - 'docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /home/palas/.caddy:/root/.caddy gcr.io/$PROJECT_ID/devops-directive-caddy:$COMMIT_SHA'
images:
 - 'gcr.io/$PROJECT_ID/devops-directive-caddy:$COMMIT_SHA'
