googleAnalytics = "UA-24019779-3"
disqusShortname = "devops-directive"

baseURL = "https://devopsdirective.com/"
languageCode = "en-us"
title = "DevOps Directive"
theme = "book"

Paginate = 6
SectionPagesMenu = "main"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
unsafe= true

[params]
  youtube = "https://www.youtube.com/channel/UC4MdpjzjPuop_qWNAvR23JA"
  linkedin = "https://www.linkedin.com/in/sid-palas-971b2329/"
  github = "https://github.com/sidpalas"

  # Set bundle to render side menu
  # if not specified file structure and weights will be used
  bookMenuBundle= "/menu" 

  # specify section of content to render as menu
  # if bookMenuBundle is not set, 'docs' is value by default
  BookSection= "docs"

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = false