name: Build and deploy (GCS)

on:
  push:
    branches:
      - gcs-github-action

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3
      
      - name: Google Cloud Platform (GCP) CLI - gcloud
        uses: actions-hub/gcloud@307.0.0
        env:
          PROJECT_ID: devops-directive-project
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: -m rsync -h "Cache-Control:private, max-age=0, no-transform" -d -r public gs://devopsdirective.com/
          cli: gsutil
