name: Build and deploy (GCS)

on:
  push:
    branches:
      - gcs-github-action

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3
      
      - name: Echo some stuff
        run: |
          ls
          ls public
