name: uptime-monitor

on:
  schedule:
    # Maximum frequency is every 5th minute
    - cron: '*/10 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://devopsdirective.com/"
        expected-statuses: "200"
