on:
  push:
    branches:
    - master
# on:
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@0.2
      with:
        url-to-hit: "https://devopsdirective.com"
        expected-statuses: "200"